### PR TITLE
Set privileged scc using clusterrole and clusterrolebinding

### LINKED ISSUE #117: Subctl join fails (error updating the privileged SCC) on ROSA cluster
**What happened**:

I tried to deploy Submariner on ROSA cluster using subctl : 

subctl join --kubecontext <xx>  broker-info.subm  --clusterid aws-rosa  --load-balancer

Deployment failed with the following error : 

Join error :

✗ Deploying the Submariner operator 
 ✓ Created operator CRDs
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
Error deploying the operator: error updating the SCC resource: error updating OpenShift privileged SCC: admission webhook "scc-validation.managed.openshift.io" denied the request: Modifying default SCCs [anyuid hostaccess hostmount-anyuid hostnetwork node-exporter nonroot privileged restricted] is not allowed

subctl version: v0.12.1

**What you expected to happen**:

Successful deployment 

**How to reproduce it (as minimally and precisely as possible)**:
see above 

**Anything else we need to know?**:
As part of Submariner deployment we update [1]  the privileged SCC users with the Submariner Service Accounts , and in ROSA clusters seems that the admission webhook controller is rejecting any changes to the privileged SCC

I was able to  add user to privileged SCC using [2] command

[1] 
https://github.com/submariner-io/subctl/blob/devel/pkg/scc/update.go#L40 

[2]
oc adm policy add-scc-to-user privileged system:serviceaccount:submariner-operator:submariner-gateway

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by yboaron**
In current implementation, the relevant submariner components obtain privileged permission by manipulating the system privileged scc CR.

Manipulating the system privileged scc is not allowed in ROSA and ARO platforms, check [1] for more details.

This PR defines privileged permission in OCP platform for the relevant components using ClusterRole and ClusterRoleBinding resources as described in [2] instead of manipulating the  system privileged scc CR.

Depend On: https://github.com/submariner-io/submariner-operator/pull/2237
Fixes: https://github.com/submariner-io/subctl/issues/117

[1]
https://github.com/openshift/managed-cluster-validating-webhooks/pull/176

[2]
https://developer.ibm.com/learningpaths/secure-context-constraints-openshift/scc-tutorial/

Signed-off-by: Yossi Boaron <yboaron@redhat.com>

### CODE REVIEW

File: pkg/scc/update.go [hunk 1]
```diff
@@ -19,54 +19,184 @@ limitations under the License.
...
+  name: submariner-privileged-scc
+subjects:
+- kind: ServiceAccount
+  name: submariner-lighthouse-coredns
+  namespace: submariner-operator
+`
+)
+
+var (
+	privilegedClusterRoleDefined = false
```
Comment (tpantelis) [inline pkg/scc/update.go]: Why is this defined globally? We really should avoid mutable global state.

File: pkg/scc/update.go [hunk 2]
```diff
@@ -19,54 +19,184 @@ limitations under the License.
...
+
+	nameToYaml = map[string]string{
```
Comment (tpantelis) [inline pkg/scc/update.go]: Once the yamls are added to the **submariner-operator** we can have the caller pass in the yaml name instead of using a hardcoded map.

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/scc/update.go (hunk 2 above)
Comment (yboaron) [reply pkg/scc/update.go]: Hmm, not sure that I understood your comment,
can you explain how the appropriate CRB YAML file should be retrieved given the component name without using something like map ?

File: pkg/scc/update.go (hunk 1 above)
Comment (yboaron) [reply pkg/scc/update.go]: To avoid calling ensure function if ClusterRole resource is already created, I guess we can delete this check.
I'll update the code

Comment (tpantelis) [reply pkg/scc/update.go]: Since the ClusterRole only need be created once, perhaps we can let the caller do it in the appropriate place.

File: pkg/scc/update.go (hunk 2 above)
Comment (tpantelis) [reply pkg/scc/update.go]: You mentioned in the PR you defined the "YAML files just to get your feedback and to simplify testing, it should move to submariner-operator repo as the rest of the embedded YAML files.". Once we do that then the caller can just pass in the desired yaml variable name directly, eg `Config_submariner_gateway_privilged_scc_clusterrolebinding_yaml`, instead of maintaining a hardcoded mapping to get it indirectly. We do that in other places.

**Review by tpantelis — CHANGES_REQUESTED** [review]

**Comment by yboaron** [comment]
The build gate is failing because this PR depends on submariner-operator changes that were merged to devel while subctl go.mod points to v0.14.0-m1

**Comment by skitt** [comment]
> The build gate is failing because this PR depends on submariner-operator changes that were merged to devel while subctl go.mod points to v0.14.0-m1

You need to update the dependency: `go get github.com/submariner-io/submariner-operator@devel` (and add the resulting changes to your commit).

**Review by sridhargaddam — APPROVED** [review]
LGTM, but I'll let @skitt @tpantelis to comment as they are more familiar with this code.

File: pkg/operator/ocp/ensure.go [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+	"k8s.io/client-go/dynamic"
+	"k8s.io/client-go/kubernetes"
+)
+
+func EnsureRBAC(dynClient dynamic.Interface, kubeClient kubernetes.Interface, namespace string) (bool, error) {
+	if !IsOcpPlatform(dynClient) {
+		return false, nil
+	}
+
+	createdCR, err := clusterrole.EnsureFromYAML(kubeClient, embeddedyamls.Config_rbac_submariner_operator_cluster_role_yaml)
```
Comment (skitt) [inline pkg/operator/ocp/ensure.go]: How about using the same structure as in `submariner/ocp`, with a data structure describing the files to apply? That way the `EnsureRBAC` function could be shared, passing in the appropriate list of `rbacInfo`s.

File: pkg/operator/ocp/ensure.go [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+		return false, errors.Wrap(err, "error provisioning the operator OCP ClusterRole resource")
+	}
+
+	createdCRB, err := clusterrolebinding.EnsureFromYAML(kubeClient, namespace,
+		embeddedyamls.Config_rbac_submariner_operator_ocp_cluster_role_binding_yaml)
+	if err != nil {
+		return false, errors.Wrap(err, "error provisioning the operator OCP ClusterRoleBinding resource")
+	}
+
+	return createdCR || createdCRB, errors.Wrap(err, "error updating the SCC resources")
```
Comment (skitt) [inline pkg/operator/ocp/ensure.go]: Here the booleans are ored, whereas in `submariner/ocp` they are anded — which should it be?

**Review by skitt — CHANGES_REQUESTED** [review]

File: pkg/operator/ocp/ensure.go (hunk 3 above)
Comment (yboaron) [reply pkg/operator/ocp/ensure.go]: Sounds good to me, I'll update the PR.
10x

File: pkg/operator/ocp/ensure.go (hunk 4 above)
Comment (yboaron) [reply pkg/operator/ocp/ensure.go]: It should be and

File: pkg/lighthouse/ocp/ensure.go [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+		return false, errors.Wrap(err, "error provisioning the CoreDNS OCP ClusterRole resource")
+	}
+
+	createdCoreDNSCRB, err := clusterrolebinding.EnsureFromYAML(kubeClient, namespace,
+		embeddedyamls.Config_rbac_lighthouse_coredns_cluster_role_binding_yaml)
+	if err != nil {
+		return false, errors.Wrap(err, "error provisioning the CoreDNS OCP ClusterRoleBinding resource")
+	}
+
+	return createdAgentCR || createdAgentCRB || createdCoreDNSCR || createdCoreDNSCRB, errors.Wrap(err, "error updating the SCC resources")
```
Comment (tpantelis) [inline pkg/lighthouse/ocp/ensure.go]: `err` will be nil here since it's checked on L54.

```suggestion
	return createdAgentCR || createdAgentCRB || createdCoreDNSCR || createdCoreDNSCRB, nil
```

File: pkg/lighthouse/ensure.go [hunk 6]
```diff
@@ -35,7 +35,7 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
 		status.Success("Created lighthouse service account and role")
 	}
 
-	if created, err := scc.Ensure(dynClient, operatorNamespace); err != nil {
+	if created, err := ocp.EnsureRBAC(dynClient, kubeClient, operatorNamespace); err != nil {
 		return err // nolint:wrapcheck // No need to wrap here
 	} else if created {
 		status.Success("Updated the privileged SCC")
```
Comment (tpantelis) [inline pkg/lighthouse/ensure.go]: Should this change (elsewhere as well)?

```suggestion
		status.Success("Updated the privileged OCP roles")
```

File: pkg/operator/ocp/ensure.go (hunk 4 above)
Comment (tpantelis) [reply pkg/operator/ocp/ensure.go]: They should be OR'ed - the intent is to return true if any were created.

Also `err` will be nil here.

File: pkg/operator/ocp/ensure.go [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+}
+
+func IsOcpPlatform(dynClient dynamic.Interface) bool {
+	sccClient := dynClient.Resource(securityv1.GroupVersion.WithResource("securitycontextconstraints"))
+	_, err := sccClient.Get(context.TODO(), "privileged", metav1.GetOptions{})
+
+	return err == nil
```
Comment (tpantelis) [inline pkg/operator/ocp/ensure.go:67]: Technically we really should check if it's a `NotFound` error and fail on any other error but I guess this is fine - if we can't access the API server then something else will likely fail.

File: pkg/submariner/ocp/ensure.go [hunk 8]
```diff
@@ -0,0 +1,88 @@
...
+			clusterRoleBindingFile: embeddedyamls.Config_rbac_submariner_diagnose_ocp_cluster_role_binding_yaml,
+		},
+		{
+			componentName:          "networkplugin-syncer",
+			clusterRoleFile:        embeddedyamls.Config_rbac_networkplugin_syncer_ocp_cluster_role_yaml,
+			clusterRoleBindingFile: embeddedyamls.Config_rbac_networkplugin_syncer_ocp_cluster_role_binding_yaml,
+		},
+	}
+
+	updateRbac := true
```
Comment (tpantelis) [inline pkg/submariner/ocp/ensure.go]:
```suggestion
	updatedRbac := false
```

File: pkg/submariner/ocp/ensure.go [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+		if err != nil {
+			return false, errors.Wrapf(err, "error provisioning the %s OCP ClusterRole resource", componentRbac.componentName)
+		}
+
+		createdCRB, err := clusterrolebinding.EnsureFromYAML(kubeClient, namespace, componentRbac.clusterRoleBindingFile)
+		if err != nil {
+			return false, errors.Wrapf(err, "error provisioning the %s OCP ClusterRoleBinding resource", componentRbac.componentName)
+		}
+
+		updateRbac = updateRbac && createdCR && createdCRB
```
Comment (tpantelis) [inline pkg/submariner/ocp/ensure.go]:
```suggestion
		updatedRbac = updatedRbac || createdCR || createdCRB
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/operator/ocp/ensure.go (hunk 4 above)
Comment (yboaron) [reply pkg/operator/ocp/ensure.go]: Hmm, but even if one of clusterrole , clusterrolebinding was created, we won't have privileged permission for the component, what am I missing here?

Comment (tpantelis) [reply pkg/operator/ocp/ensure.go]: The purpose of the return boolean is to report if something was actually created (successfully), ie if it didn't already exist, so the caller can report that to the user. A resource may already exist if `join` was previously run. The return error indicates if a creation failed.

Comment (yboaron) [reply pkg/operator/ocp/ensure.go]: Ack, 10x. will change to or

File: pkg/lighthouse/ensure.go [hunk 10]
```diff
@@ -35,10 +36,23 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
...
+			ClusterRoleFile:        embeddedyamls.Config_rbac_lighthouse_coredns_ocp_cluster_role_yaml,
+			ClusterRoleBindingFile: embeddedyamls.Config_rbac_lighthouse_coredns_cluster_role_binding_yaml,
+		},
+	}
+
+	if created, err := ocp.EnsureRBAC(dynClient, kubeClient, operatorNamespace, componentsRbac); err != nil {
 		return err // nolint:wrapcheck // No need to wrap here
 	} else if created {
-		status.Success("Updated the privileged SCC")
+		status.Success("Updated the OCP rolse")
```
Comment (skitt) [inline pkg/lighthouse/ensure.go]:
```suggestion
		status.Success("Updated the OCP roles")
```

File: pkg/operator/ensure.go [hunk 11]
```diff
@@ -56,10 +57,19 @@ func Ensure(status reporter.Interface, clientProducer client.Producer, operatorN
...
+			ClusterRoleBindingFile: embeddedyamls.Config_rbac_submariner_operator_ocp_cluster_role_binding_yaml,
+		},
+	}
+
+	if created, err := ocp.EnsureRBAC(clientProducer.ForDynamic(), clientProducer.ForKubernetes(),
+		operatorNamespace, componentsRbac); err != nil {
 		return err
 	} else if created {
-		status.Success("Updated the privileged SCC")
+		status.Success("Updated the OCP rolse")
```
Comment (skitt) [inline pkg/operator/ensure.go]:
```suggestion
		status.Success("Updated the OCP roles")
```

File: pkg/submariner/ensure.go [hunk 12]
```diff
@@ -35,10 +36,38 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
...
+			ClusterRoleFile:        embeddedyamls.Config_rbac_networkplugin_syncer_ocp_cluster_role_yaml,
+			ClusterRoleBindingFile: embeddedyamls.Config_rbac_networkplugin_syncer_ocp_cluster_role_binding_yaml,
+		},
+	}
+
+	if created, err := ocp.EnsureRBAC(dynClient, kubeClient, operatorNamespace, componentsRbac); err != nil {
 		return err // nolint:wrapcheck // No need to wrap here
 	} else if created {
-		status.Success("Updated the privileged SCC")
+		status.Success("Updated the OCP rolse")
```
Comment (skitt) [inline pkg/submariner/ensure.go]:
```suggestion
		status.Success("Updated the OCP roles")
```

**Review by skitt — CHANGES_REQUESTED** [review]
Thanks for this, there’s a small typo to fix if you don’t mind.

File: pkg/lighthouse/ensure.go [hunk 13]
```diff
@@ -35,10 +36,23 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
 		status.Success("Created lighthouse service account and role")
 	}
 
-	if created, err := scc.Ensure(dynClient, operatorNamespace); err != nil {
+	componentsRbac := []ocp.RbacInfo{
+		{
+			ComponentName:          "lighthouse-agent",
```
Comment (tpantelis) [inline pkg/lighthouse/ensure.go]:
```suggestion
			ComponentName:          names.ServiceDiscoveryComponent,
```

File: pkg/lighthouse/ensure.go [hunk 14]
```diff
@@ -35,10 +36,23 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
...
+			ClusterRoleFile:        embeddedyamls.Config_rbac_lighthouse_agent_ocp_cluster_role_yaml,
+			ClusterRoleBindingFile: embeddedyamls.Config_rbac_lighthouse_agent_ocp_cluster_role_binding_yaml,
+		},
+		{
+			ComponentName:          "lighthouse-coredns",
```
Comment (tpantelis) [inline pkg/lighthouse/ensure.go]:
```suggestion
			ComponentName:          names.LighthouseCoreDNSComponent,
```

File: pkg/operator/ensure.go [hunk 15]
```diff
@@ -56,10 +57,19 @@ func Ensure(status reporter.Interface, clientProducer client.Producer, operatorN
 		status.Success("Created operator service account and role")
 	}
 
-	if created, err := scc.Ensure(clientProducer.ForDynamic(), operatorNamespace); err != nil {
+	componentsRbac := []ocp.RbacInfo{
+		{
+			ComponentName:          "submariner-operator",
```
Comment (tpantelis) [inline pkg/operator/ensure.go]:
```suggestion
			ComponentName:          names.OperatorComponent,
```

File: pkg/submariner/ensure.go [hunk 16]
```diff
@@ -35,10 +36,38 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
 		status.Success("Created submariner service account and role")
 	}
 
-	if created, err := scc.Ensure(dynClient, operatorNamespace); err != nil {
+	componentsRbac := []ocp.RbacInfo{
+		{
+			ComponentName:          "submariner-gateway",
```
Comment (tpantelis) [inline pkg/submariner/ensure.go]:
```suggestion
			ComponentName:          names.GatewayComponent,
```

File: pkg/submariner/ensure.go [hunk 17]
```diff
@@ -35,10 +36,38 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
...
+			ClusterRoleFile:        embeddedyamls.Config_rbac_submariner_gateway_ocp_cluster_role_yaml,
+			ClusterRoleBindingFile: embeddedyamls.Config_rbac_submariner_gateway_ocp_cluster_role_binding_yaml,
+		},
+		{
+			ComponentName:          "submariner-route-agent",
```
Comment (tpantelis) [inline pkg/submariner/ensure.go]:
```suggestion
			ComponentName:          names.RouteAgentComponent,
```

File: pkg/submariner/ensure.go [hunk 18]
```diff
@@ -35,10 +36,38 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
...
+			ClusterRoleFile:        embeddedyamls.Config_rbac_submariner_route_agent_ocp_cluster_role_yaml,
+			ClusterRoleBindingFile: embeddedyamls.Config_rbac_submariner_route_agent_ocp_cluster_role_binding_yaml,
+		},
+		{
+			ComponentName:          "submariner-globalnet",
```
Comment (tpantelis) [inline pkg/submariner/ensure.go]:
```suggestion
			ComponentName:          names.GlobalnetComponent,
```

File: pkg/submariner/ensure.go [hunk 19]
```diff
@@ -35,10 +36,38 @@ func Ensure(status reporter.Interface, kubeClient kubernetes.Interface, dynClien
...
+			ClusterRoleFile:        embeddedyamls.Config_rbac_submariner_globalnet_ocp_cluster_role_yaml,
+			ClusterRoleBindingFile: embeddedyamls.Config_rbac_submariner_globalnet_ocp_cluster_role_binding_yaml,
+		},
+		{
+			ComponentName:          "submariner-diagnose",
+			ClusterRoleFile:        embeddedyamls.Config_rbac_submariner_diagnose_ocp_cluster_role_yaml,
+			ClusterRoleBindingFile: embeddedyamls.Config_rbac_submariner_diagnose_ocp_cluster_role_binding_yaml,
+		},
+		{
+			ComponentName:          "networkplugin-syncer",
```
Comment (tpantelis) [inline pkg/submariner/ensure.go]:
```suggestion
			ComponentName:          names.NetworkPluginSyncerComponent,
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by skitt** [comment]
https://github.com/submariner-io/subctl/pull/282 should fix the system tests.

**Review by skitt — APPROVED** [review]
