### PR TITLE
Use clusterID instead of clusterName to get endpoint

### LINKED ISSUE #2332: OCP 4.12: failed to run `subctl diagnose firewall inter-cluster`
**What happened**:
running `subctl diagnose firewall inter-cluster` failed:
```
subctl diagnose firewall inter-cluster --context cluster-b1 --remotecontext cluster-a1
 ✗ Checking if tunnels can be setup on the gateway node of cluster "maafried-cluster-b1" 
 ✗ Error: the gateway on cluster "maafried-cluster-a1" does not have an active connection to cluster "maafried-cluster-b1"
 ✗ Error retrieving the gateway IP of cluster "maafried-cluster-b1": Error: the gateway on cluster "maafried-cluster-a1" does not have an active connection to cluster "maafried-cluster-b1"
 ✗ Could not determine if Tunnels can be established on the gateway node of cluster "maafried-cluster-b1"

subctl version: v0.14.0-rc2
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
OCP 4.12 on AWS,
submariner 0.14.0-rc2
[maafried-cluster-a1.tar.gz](https://github.com/submariner-io/submariner-operator/files/9952107/maafried-cluster-a1.tar.gz)
[maafried-cluster-b1.tar.gz](https://github.com/submariner-io/submariner-operator/files/9952109/maafried-cluster-b1.tar.gz)

- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Jaanki**
`clusterName` is the cluster name as populated in kubeconfig. When a cluster is joined using `--clusterid` flag, cluster is joined with `clusterid` and not `clusterName`. This PR updated the diagnose logic to look for endpoints based on the `clusterID` and not the `clusterName`.

Closes: [#2332](https://github.com/submariner-io/submariner-operator/issues/2332)

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

**Review by sridhargaddam — DISMISSED** [review]

File: pkg/diagnose/firewall.go [hunk 1]
```diff
@@ -244,7 +244,7 @@ func verifyConnectivity(localClusterInfo, remoteClusterInfo *cluster.Info, names
 
 	defer sPod.Delete()
 
-	gatewayPodIP, err := getGatewayIP(remoteClusterInfo, localClusterInfo.Name, status)
+	gatewayPodIP, err := getGatewayIP(remoteClusterInfo, localClusterInfo.Submariner.Status.ClusterID, status)
 	if err != nil {
 		return status.Error(err, "Error retrieving the gateway IP of cluster %q", localClusterInfo.Name)
```
Comment (sridhargaddam) [inline pkg/diagnose/firewall.go:249]: maybe we should use "localClusterInfo.Submariner.Status.ClusterID" in the log message as well?

**Review by tpantelis — APPROVED** [review]

File: pkg/diagnose/firewall.go (hunk 1 above)
Comment (Jaanki) [reply pkg/diagnose/firewall.go:249]: There are many other places, spanning across other `subctl commands`, where this change is needed. I intend to do this in a separate PR.

Comment (sridhargaddam) [reply pkg/diagnose/firewall.go:249]: Yes, they are in the log messages only and can be clubbed with this PR too. But anyways, I'm fine if you want to handle it in a separate PR.

**Review by sridhargaddam — APPROVED** [review]
