### PR TITLE
Include image-override as a firewall subcmd

### LINKED ISSUE #597: --image-override doesn’t work everywhere
A number of `subctl` commands support an `--image-override` flag, but it doesn’t actually work everywhere; we need to test all the variants and identify gaps.

To test the flag, specify an invalid `nettest` image using `--image-override=submariner-nettest=…` and check that the command fails.

- [x] [Include image-override as a firewall subcmd](https://github.com/submariner-io/subctl/pull/598)
- [x] [Support image-override in diagnose all command](https://github.com/submariner-io/subctl/pull/602)

### PR DESCRIPTION
**Pull request by sridhargaddam**
Currently the image-override flag was added to the main subctl diagnose firewall command and was hence ignored when it was passed to the sub-command like intra-cluster, inter-cluster etc. This PR fixes it.

Usage:
subctl diagnose firewall intra-cluster --image-override=...

Partially fixes: https://github.com/submariner-io/subctl/issues/597

### CODE REVIEW

File: cmd/subctl/diagnose.go [hunk 1]
```diff
@@ -195,6 +194,9 @@ func addDiagnoseFirewallSubCommands() {
 	diagnoseFirewallNatDiscoveryRestConfigProducer.SetupFlags(diagnoseFirewallNatDiscovery.Flags())
 	addDiagnoseFWConfigFlags(diagnoseFirewallNatDiscovery)
 
+	diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallVxLANCmd.Flags())
+	diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallTunnelCmd.Flags())
+	diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallNatDiscovery.Flags())
```
Comment (skitt) [inline cmd/subctl/diagnose.go:199]: Does this work with all three variants? IME sharing a flag variable in this way only works with one of the commands, that’s why there’s a `kube-proxy` variant and a `firewall` variant. I think the fix should be to change the original

    diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallCmd.Flags())

line to

    diagnose.AddFirewallImageOverrideFlag(diagnoseFirewallCmd.PersistentFlags())

**Review by skitt — CHANGES_REQUESTED** [review]

**Comment by sridhargaddam** [comment]
Sample output:

```
subctl diagnose firewall inter-cluster --image-override=submariner-nettest=ip-172-31-30-49.us-east-2.compute.internal:8443/rhacm2/nettest-rhel8@sha256:94dbe33bd8f5030aa828ac133925c4ac3b710f64c26b45ff290ca05dfb2be0c0 --context hub-admin --remotecontext spoke-admin
⢎⠁ Checking if tunnels can be setup on the gateway node of cluster "hub-cluster"
 ✓ Checking if tunnels can be setup on the gateway node of cluster "hub-cluster" 
 ✓ Tunnels can be established on the gateway node of cluster "hub-cluster"

subctl diagnose firewall intra-cluster --image-override=submariner-nettest=ip-172-31-30-49.us-east-2.compute.internal:8443/rhacm2/nettest-rhel8@sha256:94dbe33bd8f5030aa828ac133925c4ac3b710f64c26b45ff290ca05dfb2be0c0 
Cluster "hub-cluster"
⢎⡠ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed  
 ✓ The firewall configuration allows intra-cluster VXLAN traffic
 
subctl diagnose firewall nat-discovery --image-override=submariner-nettest=ip-172-31-30-49.us-east-2.compute.internal:8443/rhacm2/nettest-rhel8@sha256:94dbe33bd8f5030aa828ac133925c4ac3b710f64c26b45ff290ca05dfb2be0c0 --context hub-admin --remotecontext spoke-admin --verbose 
 ✓ Checking if nat-discovery port is opened on the gateway node of cluster "hub-cluster" 
 ✓ nat-discovery port is allowed in the cluster "hub-cluster"

```

File: cmd/subctl/diagnose.go (hunk 1 above)
Comment (sridhargaddam) [reply cmd/subctl/diagnose.go:199]: Yes it works with all the three variants, please see - https://github.com/submariner-io/subctl/pull/598#issuecomment-1461986305

**Review by skitt — APPROVED** [review]

**Review by MaxBab — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Comment by sridhargaddam** [comment]
Backport PR (0.14 branch): https://github.com/submariner-io/subctl/pull/603
