### PR TITLE
Ensure cluster ID is unique on join

### LINKED ISSUE #705: `join` should not allow joining 2 clusters with same cluster ID
**What happened**:
When I am joining 2nd cluster using the same `--clusterid` flag value as used for joining the first cluster, the operation is successful.

**What you expected to happen**:
`join` should have failed stating that a cluster with this clusterid is already joined.

**How to reproduce it (as minimally and precisely as possible)**:
Join cluster1 and then cluster2 using `--clusterid cluster1id` flag.

```
$ subctl join --kubeconfig output/kubeconfigs/kind-config-cluster1 --clusterid cluster1id broker-info.subm
 ✓ broker-info.subm indicates broker is at https://172.19.0.4:6443
 ✓ Discovering network details
        Network plugin:  kindnet
        Service CIDRs:   [100.66.0.0/16]
        Cluster CIDRs:   [10.130.0.0/16]
 ✓ Retrieving the gateway nodes
 ✓ Retrieving all worker nodes
? Which node should be used as the gateway? cluster1-control-plane
 ✓ Labeling node "cluster1-control-plane" as a gateway
 ✓ Gathering relevant information from Broker
 ✓ Retrieving Globalnet information from the Broker
 ✓ Validating Globalnet configuration
 ✓ Deploying the Submariner operator 
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
 ✓ Created submariner service account and role
 ✓ Created lighthouse service account and role
 ✓ Creating SA for cluster 
 ✓ Connecting to Broker
 ✓ Deploying submariner
 ✓ Submariner is up and running

$ subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 --clusterid cluster1id broker-info.subm
 ✓ broker-info.subm indicates broker is at https://172.19.0.4:6443
 ✓ Discovering network details
        Network plugin:  kindnet
        Service CIDRs:   [100.67.0.0/16]
        Cluster CIDRs:   [10.131.0.0/16]
 ✓ Retrieving the gateway nodes
 ✓ Retrieving all worker nodes
? Which node should be used as the gateway? cluster2-control-plane
 ✓ Labeling node "cluster2-control-plane" as a gateway
 ✓ Gathering relevant information from Broker
 ✓ Retrieving Globalnet information from the Broker
 ✓ Validating Globalnet configuration
 ✓ Deploying the Submariner operator 
 ✓ Created operator CRDs
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
 ✓ Created submariner service account and role
 ✓ Created lighthouse service account and role
 ✓ Deployed the operator successfully
 ✓ Creating SA for cluster
 ✓ Connecting to Broker
 ✓ Deploying submariner
 ✓ Submariner is up and running
```

**Anything else we need to know?**:
`subctl show` shows endpoints with the same clusterid for both the clusters.

```
$ subctl show all
Cluster "cluster2"
 ✓ Detecting broker(s)
 ✓ No brokers found

 ✗ Showing Connections
 ✗ No connections found

 ✓ Showing Endpoints
CLUSTER      ENDPOINT IP   PUBLIC IP       CABLE DRIVER   TYPE    
cluster1id   172.19.0.7    49.207.231.56   libreswan      local   

 ✓ Showing Gateways
NODE                     HA STATUS   SUMMARY                    
cluster2-control-plane   active      There are no connections   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  kindnet
        Service CIDRs:   [100.67.0.0/16]
        Cluster CIDRs:   [10.131.0.0/16]

 ✓ Showing versions
COMPONENT                       REPOSITORY           VERSION      
submariner-gateway              quay.io/submariner   0.15.0-rc1   
submariner-routeagent           quay.io/submariner   0.15.0-rc1   
submariner-operator             quay.io/submariner   0.15.0-rc1   
submariner-lighthouse-agent     quay.io/submariner   0.15.0-rc1   
submariner-lighthouse-coredns   quay.io/submariner   0.15.0-rc1   

Cluster "cluster1"
 ✓ Detecting broker(s)
NAMESPACE   NAME                COMPONENTS                        GLOBALNET   GLOBALNET CIDR   DEFAULT GLOBALNET SIZE   DEFAULT DOMAINS   
test-ns     submariner-broker   service-discovery, connectivity   no          242.0.0.0/8      65536                                      

 ✗ Showing Connections
 ✗ No connections found

 ✓ Showing Endpoints
CLUSTER      ENDPOINT IP   PUBLIC IP       CABLE DRIVER   TYPE    
cluster1id   172.19.0.4    49.207.231.56   libreswan      local   

 ✓ Showing Gateways
NODE                     HA STATUS   SUMMARY                    
cluster1-control-plane   active      There are no connections   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  kindnet
        Service CIDRs:   [100.66.0.0/16]
        Cluster CIDRs:   [10.130.0.0/16]

 ✓ Showing versions
COMPONENT                       REPOSITORY           VERSION      
submariner-gateway              quay.io/submariner   0.15.0-rc1   
submariner-routeagent           quay.io/submariner   0.15.0-rc1   
submariner-operator             quay.io/submariner   0.15.0-rc1   
submariner-lighthouse-agent     quay.io/submariner   0.15.0-rc1   
submariner-lighthouse-coredns   quay.io/submariner   0.15.0-rc1   


subctl version: v0.15.0-rc1
```

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```
$ subctl diagnose all
Cluster "cluster1"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.25.3" is supported

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking if gateway metrics are accessible from non-gateway nodes 
 ✓ The gateway metrics are accessible

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("kindnet") is supported
 ✗ Checking gateway connections
 ✗ There are no active connections on gateway "cluster1-control-plane"
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✗ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed
 ✗ Unable to obtain a remote endpoint: endpoints.submariner.io "remote Endpoint" not found
 ✓ Globalnet is not installed - skipping

 ✓ Checking if services have been exported properly
 ✓ All services have been exported properly

Cluster "cluster2"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.25.3" is supported

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking if gateway metrics are accessible from non-gateway nodes 
 ✓ The gateway metrics are accessible

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("kindnet") is supported
 ✗ Checking gateway connections
 ✗ There are no active connections on gateway "cluster2-control-plane"
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✗ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed
 ✗ Unable to obtain a remote endpoint: endpoints.submariner.io "remote Endpoint" not found
 ✓ Globalnet is not installed - skipping

 ✓ Checking if services have been exported properly
 ✓ All services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.15.0-rc1
```

- Gather information (use `subctl gather`)
It also affects few file names on running `gather` as evident from attached screenshots.

cluster1_summary.html snippet
cluster1_summary html

cluster2_summary.html snippet
cluster2_summary html

- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tpantelis**
Fixes https://github.com/submariner-io/subctl/issues/705

### CODE REVIEW

File: pkg/join/join.go [hunk 1]
```diff
@@ -212,3 +223,35 @@ func isValidCustomCoreDNSConfig(corednsCustomConfigMap string) error {
...
+
+func ensureUniqueCluster(ctx context.Context, clusterID string, brokerProducer client.Producer, brokerNamespace string,
+	localProducer client.Producer, operatorNamespace string, status reporter.Interface,
+) error {
+	err := localProducer.ForGeneral().Get(ctx, controllerClient.ObjectKey{
+		Namespace: operatorNamespace,
+		Name:      clusterID,
+	}, &submarinerv1.Cluster{})
+
+	if !resource.IsNotFoundErr(err) {
```
Comment (aswinsuryan) [inline pkg/join/join.go:235]: if found here? should we go to next step?

Comment (tpantelis) [reply pkg/join/join.go:235]: No that means submariner was already installed. We only want to check for dup cluster ID if it's a new install.

**Review by aswinsuryan — APPROVED** [review]

**Review by vthapar — APPROVED** [review]
