### PR TITLE
Display proper output message on `subctl show brokers`

### LINKED ISSUE #167: `subctl show brokers` output empty on non-broker cluster
**What happened**:
On a non-broker cluster (cluster2 in this case), `subctl show brokers` doesn't print anything. Just a blank line.
```
$ subctl show brokers
Cluster "cluster1"
 ✓ Detecting broker(s)
NAMESPACE                NAME                     COMPONENTS                        GLOBALNET ENABLED   GLOBALNET CIDR       DEFAULT GLOBALNET SIZE    DEFAULT DOMAINS                         
submariner-k8s-broker    submariner-broker        service-discovery, connectivity   false               242.0.0.0/8          65536                                                             

Cluster "cluster2"
 ✓ Detecting broker(s)


```

**What you expected to happen**:
It should print something meaningful like "Broker is not installed on this cluster".

**How to reproduce it (as minimally and precisely as possible)**:
Run `subctl show brokers`

**Anything else we need to know?**:
This also affects `subctl show all`

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Jaanki**
when broker is not installed on the cluster.

Currently a blank line is displayed. Instead display that "No brokers
found" when a broker is not installed on the cluster.

The output will look like

$ cmd/bin/subctl-devel-59cc4f5-linux-amd64 show brokers
Cluster "cluster2"
 ✓ Detecting broker(s)
 ✓ No brokers found

Closes: #167
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

File: internal/show/brokers.go [hunk 1]
```diff
@@ -45,6 +46,7 @@ func Brokers(clusterInfo *cluster.Info, status reporter.Interface) bool {
 
 	brokers := brokerList.Items
 	if len(brokers) == 0 {
+		fmt.Println("   Broker not installed")
```
Comment (dfarrell07) [inline internal/show/brokers.go]: I see your sample output in the commit message, and to me it looks like it would need an extra space to align. I wonder if we need the complexity of indentation at all? :shrug:

Comment (tpantelis) [reply internal/show/brokers.go]: Use the status to report the message.

```suggestion
		status.Success("No brokers found")
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: internal/show/brokers.go (hunk 1 above)
Comment (Jaanki) [reply internal/show/brokers.go]: While trying locally, it showed up correctly. Indentation looks nice. But then all other outputs (except for show network) don't have indentation. I am also wondering if we can use status.success here.

Comment (Jaanki) [reply internal/show/brokers.go]: "No brokers found" was my initial thought. But not installed sounds more accurate.

Comment (Jaanki) [reply internal/show/brokers.go]: Or should we use `status.Warning` like it is done when `submariner` is not installed in the cluster?

Comment (Jaanki) [reply internal/show/brokers.go]: @tpantelis @skitt WDYT ^ ?

Comment (tpantelis) [reply internal/show/brokers.go]: A warning indicates it could be a problem but it's not required for a broker to be installed so this doesn't qualify as a warning.

**Review by sridhargaddam — APPROVED** [review]

**Review by mkolesnik — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]
